<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class DocumentsSeeder extends Seeder
{
    public function run()
    {
        $documents = [
            [
                'code' => '1010',
                'name' => 'Employee Personal Action Form (EPAF) - TX',
                'description' => 'Employee personal information and action form for Texas',
                'path' => 'documents/fillable-forms/1010-Employee Personal Action Form (EPAF)-TX.pdf',
                'file_name' => '1010-Employee Personal Action Form (EPAF)-TX.pdf',
                'mime_type' => 'application/pdf',
                'file_size' => 103949,
                'is_fillable' => true,
                'is_active' => true,
            ],
            [
                'code' => '1020',
                'name' => 'Employment Application',
                'description' => 'Standard employment application form',
                'path' => 'documents/fillable-forms/1020-Employment Application_1123.pdf',
                'file_name' => '1020-Employment Application_1123.pdf',
                'mime_type' => 'application/pdf',
                'file_size' => 201527,
                'is_fillable' => true,
                'is_active' => true,
            ],
            [
                'code' => '1021',
                'name' => 'Equal Employment Opportunity Data Form',
                'description' => 'EEO data collection form',
                'path' => 'documents/fillable-forms/1021-Equal Employment Opportunity Data Form.pdf',
                'file_name' => '1021-Equal Employment Opportunity Data Form.pdf',
                'mime_type' => 'application/pdf',
                'file_size' => 115753,
                'is_fillable' => true,
                'is_active' => true,
            ],
            [
                'code' => '1050',
                'name' => 'Skills Checklist - Associates',
                'description' => 'Skills assessment checklist for associates',
                'path' => 'documents/fillable-forms/1050-Skills Checklist-Associates.pdf',
                'file_name' => '1050-Skills Checklist-Associates.pdf',
                'mime_type' => 'application/pdf',
                'file_size' => 664121,
                'is_fillable' => true,
                'is_active' => true,
            ],
            [
                'code' => '1060',
                'name' => 'Request for Reference',
                'description' => 'Form to request employment references',
                'path' => 'documents/fillable-forms/1060-Request for Reference.pdf',
                'file_name' => '1060-Request for Reference.pdf',
                'mime_type' => 'application/pdf',
                'file_size' => 105843,
                'is_fillable' => true,
                'is_active' => true,
            ],
            [
                'code' => '1070',
                'name' => 'Background Check Authorization - TX',
                'description' => 'Authorization form for background checks in Texas',
                'path' => 'documents/fillable-forms/1070-Background Check Authorization_TX.pdf',
                'file_name' => '1070-Background Check Authorization_TX.pdf',
                'mime_type' => 'application/pdf',
                'file_size' => 112487,
                'is_fillable' => true,
                'is_active' => true,
            ],
            [
                'code' => '1201',
                'name' => 'Handbook Acknowledgment - TX',
                'description' => 'Acknowledgement of employee handbook receipt for Texas',
                'path' => 'documents/fillable-forms/1201-Handbook Acknowledgment_TX.pdf',
                'file_name' => '1201-Handbook Acknowledgment_TX.pdf',
                'mime_type' => 'application/pdf',
                'file_size' => 75908,
                'is_fillable' => true,
                'is_active' => true,
            ],
            [
                'code' => '1202',
                'name' => 'Orientation Acknowledgements',
                'description' => 'Acknowledgement forms for orientation completion',
                'path' => 'documents/fillable-forms/1202-Orientation Acknowledgements.pdf',
                'file_name' => '1202-Orientation Acknowledgements.pdf',
                'mime_type' => 'application/pdf',
                'file_size' => 102355,
                'is_fillable' => true,
                'is_active' => true,
            ],
            [
                'code' => '1203',
                'name' => 'Orientation Curriculum - TX',
                'description' => 'Orientation curriculum acknowledgement for Texas',
                'path' => 'documents/fillable-forms/1203-Orientation Curriculum_TX.pdf',
                'file_name' => '1203-Orientation Curriculum_TX.pdf',
                'mime_type' => 'application/pdf',
                'file_size' => 94052,
                'is_fillable' => true,
                'is_active' => true,
            ],
            [
                'code' => '1204',
                'name' => 'Care Associate Availability',
                'description' => 'Availability schedule for care associates',
                'path' => 'documents/fillable-forms/1204-Care Associate Availability.pdf',
                'file_name' => '1204-Care Associate Availability.pdf',
                'mime_type' => 'application/pdf',
                'file_size' => 78752,
                'is_fillable' => true,
                'is_active' => true,
            ],
            [
                'code' => '1220',
                'name' => 'Abuse and Neglect Policy',
                'description' => 'Acknowledgement of abuse and neglect policies',
                'path' => 'documents/fillable-forms/1220-Abuse_Neglect Policy.pdf',
                'file_name' => '1220-Abuse_Neglect Policy.pdf',
                'mime_type' => 'application/pdf',
                'file_size' => 93746,
                'is_fillable' => true,
                'is_active' => true,
            ],
            [
                'code' => '1530',
                'name' => 'Care Associate Schedule Acknowledgement',
                'description' => 'Acknowledgement of care associate schedule',
                'path' => 'documents/fillable-forms/1530-Care Associate Schedule Acknowledgement.pdf',
                'file_name' => '1530-Care Associate Schedule Acknowledgement.pdf',
                'mime_type' => 'application/pdf',
                'file_size' => 73648,
                'is_fillable' => true,
                'is_active' => true,
            ],
            [
                'code' => '1600',
                'name' => 'Emergency Contact Information',
                'description' => 'Form for collecting emergency contact details',
                'path' => 'documents/fillable-forms/1600-Emergency Contact Information.pdf',
                'file_name' => '1600-Emergency Contact Information.pdf',
                'mime_type' => 'application/pdf',
                'file_size' => 89554,
                'is_fillable' => true,
                'is_active' => true,
            ],
            [
                'code' => '1720',
                'name' => 'Hepatitis B Consent-Declination',
                'description' => 'Hepatitis B vaccination consent or declination form',
                'path' => 'documents/fillable-forms/1720-Hepatitis B_Consent-Declination.pdf',
                'file_name' => '1720-Hepatitis B_Consent-Declination.pdf',
                'mime_type' => 'application/pdf',
                'file_size' => 89800,
                'is_fillable' => true,
                'is_active' => true,
            ],
            [
                'code' => '1740',
                'name' => 'Pre-Employment Drug Consent',
                'description' => 'Consent form for pre-employment drug testing',
                'path' => 'documents/fillable-forms/1740-Pre-Employment Drug Consent-RVSD.pdf',
                'file_name' => '1740-Pre-Employment Drug Consent-RVSD.pdf',
                'mime_type' => 'application/pdf',
                'file_size' => 90731,
                'is_fillable' => true,
                'is_active' => true,
            ],
            [
                'code' => '2900',
                'name' => 'ID Agreement',
                'description' => 'Identification agreement form',
                'path' => 'documents/fillable-forms/2900-ID Agreement.pdf',
                'file_name' => '2900-ID Agreement.pdf',
                'mime_type' => 'application/pdf',
                'file_size' => 80657,
                'is_fillable' => true,
                'is_active' => true,
            ],
            [
                'code' => '4000',
                'name' => 'Nondisclosure and Noncompete - TX',
                'description' => 'Non-disclosure and non-compete agreement for Texas',
                'path' => 'documents/fillable-forms/4000-Nondisclosure_Noncompete_TX.pdf',
                'file_name' => '4000-Nondisclosure_Noncompete_TX.pdf',
                'mime_type' => 'application/pdf',
                'file_size' => 102433,
                'is_fillable' => true,
                'is_active' => true,
            ],
            [
                'code' => 'I-9',
                'name' => 'I-9',
                'description' => 'Employment Eligibility Verification (Revised August 2023)',
                'path' => 'documents/fillable-forms/Revised I-9 (Aug. 2023).pdf',
                'file_name' => 'Revised I-9 (Aug. 2023).pdf',
                'mime_type' => 'application/pdf',
                'file_size' => 488957,
                'is_fillable' => true,
                'is_active' => true,
            ],
            [
                'code' => 'W-4',
                'name' => 'W-4',
                'description' => 'Employee\'s Withholding Certificate (2023)',
                'path' => 'documents/fillable-forms/W-4 2023.pdf',
                'file_name' => 'W-4 2023.pdf',
                'mime_type' => 'application/pdf',
                'file_size' => 188715,
                'is_fillable' => true,
                'is_active' => true,
            ],
        ];

        foreach ($documents as $document) {
            DB::table('documents')->updateOrInsert(
                ['code' => $document['code']],
                $document
            );
        }
    }
}